### ISSUE TITLE
No double booking

### ISSUE THREAD

**Issue by oliverbarnes** [BlueRidgeLabs/kimball#36]
Another escapee from the email scheduling sprint.

* Time slots created for one event shouldn't be available to other events
* Time slots reserved by a person shouldn't be available to other invited people
* If responding to an outdated invitation and selecting a reserved time slot, person should see an error explaining what happened, and the page refreshed with the remaining available slots

**Comment by marcoow** [comment]
> If responding to an outdated invitation and selecting a reserved time slot, person should receive an email explaining what happened, and showing the remaining available slots

Why would the person receive an email explaining the error? Isn't the situation that the person goes to the website where we render the available time slots and then before the person selects a time slot and submits the form another person reserves that time slot so that submitting the form will fail as the time slot is no longer available? In this case we'd just display an error on the page.

**Comment by oliverbarnes** [comment]
Hmm, you're right, I think I had the SMS scheduling in mind when writing this :) updating

**Comment by cromulus** [comment]
A key component here is that time slots that are booked for a user shouldn't be made available to other persons to book.

The exclusion looks something like this:
```
validates :start_time, :end_time, overlap: { exclude_edges: %w(start_time end_time), scope: 'person_id' }
validates :start_time, :end_time, overlap: { exclude_edges: %w(start_time end_time), scope: 'user_id' }
```

This is using the [validates_overlap](https://github.com/robinbortlik/validates_overlap) gem.

**Comment by ganeshbsub** [comment]
We were discussing exactly that. Didn't know about the gem. Thanks! :+1:
